### ISSUE TITLE
Error Resource temporarily unavailable Cannot lock port

### ISSUE THREAD

**Issue by solowalker27** [anoff/serial-io#43]
- serial-io version 1.1
- node version 12.16.3

I'm using serial-io to connect to a BenQ Projector from a Raspberry Pi in a homebridge context. In case you're unfamiliar, homebridge is a server that allows unapproved devices to be exposed to Apple HomeKit. As such, there may be instances where serial calls are made frequently. My problem is the server near constantly gets the error:

`Error Resource temporarily unavailable Cannot lock port`

when creating a serial connection, either via just `serialIo.send()` or `serialIo.connect()` then `serialIo.send()`. I'm pretty new to serial connections and not that knowledgeable of node/javascript as this is just a side project so it's totally possible I'm using this package incorrectly, or at least inefficiently in this context. Here's my code where I create the connection:

https://github.com/solowalker27/homebridge-benq-projector/blob/serial-io/index.js#L77

And where I use it:

https://github.com/solowalker27/homebridge-benq-projector/blob/serial-io/index.js#L100

Any help or tips you could give would be much appreciated. Thanks.

**Comment by anoff** [comment]
Hey @solowalker27,
the `serialio.connect()` returns a `Connection` object. When you want to send any messages over this connection you should invoke the `.send()` method on the returned object.

In your case that would mean `this.serial.send(payload)`.

I don't really understand how https://github.com/solowalker27/homebridge-benq-projector/blob/serial-io/index.js#L100 will work because the `serial` object does not seem to be defined at all (or am I missing something?).
For all the other functions I see you are using the `serialio.send()` method that will try to open another connection to the same port. Since you already opened a _permanent_ connection on L77 you will receive the resource unavailable error.

What you should try: keep L77 as you have it and for all functions where you want to `send()` refer to the `this.serial`(Connection) object that you created in your constructor. Please note that the `conntion.send()` method has a [different API](https://github.com/anoff/serial-io#connectionsendcontent-options) than the `serialio.send()` as you do not need to specify the target port + baudrate options anymore.

Little bit of background:
The `serialio.send()` method is really made for a "stateless" environment where you want to send a single command without dealing with all the connection stuff around it. However with multiple requests happening that will introduce an awful lot of latency (connection buildup, message send, message receive, connection close) and potential resource lock errors like you are experiencing them.

PS: Yesterday I published a new version of the package that upgraded all the dependencies, many of the previous dependencies have minor vulnerabilities. There was also a major version change in the underlying serialport package. I _hope_ nothing broke (at least my tests went back to green) and it should be an easy upgrade for users.

**Comment by solowalker27** [comment]
Ugh, that’s embarrassing. Nothing like getting a second pair of eyes on your code only to realize you haven’t done anything like you thought you had…

As part of my own troubleshooting I had tried to have every function call `.send()` directly instead of using the one function that did. No wonder it’s not working. I’ll update them all and try again.

I had been using another set of functions that someone else had written that managed a serial connection directly with serialPort but I was having major performance problems like you implied I could have here with a single connection, though. I was struggling there to figure out how to improve it to mitigate those. I really hope I either don’t have them at all with serial-io, or at least that with the abstraction  layer they’re easier to deal with. Thanks for the review.

**Comment by solowalker27** [comment]
Okay, I've fixed those things but now it's still not working and giving another error.
`"Failed to get power state: TypeError: serial.send is not a function"`

I get the same thing when using the node REPL.

```
$ node
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> const serialio = require('serial-io');
undefined
> const connection = serialio.connect('/dev/ttyUSB0', {baudRate:115200})
undefined
> const response = await connection.send('\r*pow=?#\r')
const response = await connection.send('\r*pow=?#\r')
                 ^^^^^

Uncaught SyntaxError: await is only valid in async function
> connection.send('\r*pow=?#\r')
Uncaught TypeError: connection.send is not a function
>
```

**Comment by anoff** [comment]
Depending on your usecase you might be better of using `serialport` directly. I wrote `serial-io` mainly as a wrapper for ping-pong communication scenarios where you want to send a command and read the response. It doesn't do much more than that.

The `await` keyword only works in `async function () {` definitions. The example doesn't portray that properly.
Also could you update to `v1.2.0` of the package, that will change the serialio.connect behavior a tiny bit (otherwise the example won't work either).

When you're working in REPL you could try:

```javascript
const serialio = require('serial-io')

async function sendAndLog(text) {
    const response = await connection.send('hello device\n')
    console.log(response)
}

const connection = serialio.connect('/my/device')

sendAndLog('\r*pow=?#\r')
```

Instead of using `await` you can just continue using `.then()` Promise chaining as you already do in your code.

```javascript
const serialio = require('serial-io')
const connection = serialio.connect('/my/device')
connection.send('hello device\n')
    .then(response => {
    console.log(response)
}
```

**Comment by solowalker27** [comment]
Sending a command and then reading the response is literally all I want to do, from my perspective. But again, that could just be because I may understand everything I'm doing. I feel like this will do what I want if I can just figure out how to do it the right way. For now, I've updated the package and done some tweaking to try to give it more time to close connections and have added a very simple queue system. I still get the error messages but things seem to be working fine enough for me now if I just ignore them. If it causes real problems in the future I may revisit.

Thanks again for the help and package.
